
package Client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GeneralSecurityException", targetNamespace = "http://example/")
public class GeneralSecurityException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GeneralSecurityException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GeneralSecurityException_Exception(String message, GeneralSecurityException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GeneralSecurityException_Exception(String message, GeneralSecurityException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: Client.GeneralSecurityException
     */
    public GeneralSecurityException getFaultInfo() {
        return faultInfo;
    }

}
