
package Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws MessagingException_Exception
     * @throws GeneralSecurityException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://example/", className = "Client.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://example/", className = "Client.SayHelloWorldFromResponse")
    @Action(input = "http://example/HelloWorld/sayHelloWorldFromRequest", output = "http://example/HelloWorld/sayHelloWorldFromResponse", fault = {
        @FaultAction(className = GeneralSecurityException_Exception.class, value = "http://example/HelloWorld/sayHelloWorldFrom/Fault/GeneralSecurityException"),
        @FaultAction(className = MessagingException_Exception.class, value = "http://example/HelloWorld/sayHelloWorldFrom/Fault/MessagingException")
    })
    public void sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws GeneralSecurityException_Exception, MessagingException_Exception
    ;

}
